apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetmvcwebapp
spec:
  selector:
    matchLabels:
      app: aspnetmvcwebapp
  template:
    metadata:
      labels:
        app: aspnetmvcwebapp # the label for the pods and the deployments
    spec:
      containers:
      - name: aspnetmvcwebapp
        image: acrdemo20201204.azurecr.io/aspnetmvcwebapp:3
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # the application listens to this port
      nodeSelector:
        kubernetes.io/os: windows